package dispatch

import "text/template"

// installScriptParams holds the parameters for install script template rendering.
type installScriptParams struct {
	ServerHost string // HTTP host, e.g. "192.168.1.100:8080"
	GRPCAddr   string // gRPC address, e.g. "192.168.1.100:9090"
	EnrollToken string
	BinaryURL  string // full GitHub release download URL
	Version    string
	Platform   string
	Arch       string
	BinaryName string // "scout" or "scout.exe"
}

var unixInstallTemplate = template.Must(template.New("unix-install").Parse(`#!/usr/bin/env bash
set -euo pipefail

# SubNetree Scout Agent Installer
# Version: {{.Version}}
# Platform: {{.Platform}}/{{.Arch}}
# Generated by SubNetree server at {{.ServerHost}}

# --- Check root ---
if [ "$EUID" -ne 0 ]; then
  echo "ERROR: This script must be run as root (use sudo)." >&2
  exit 1
fi

BINARY_URL="{{.BinaryURL}}"
BINARY_NAME="{{.BinaryName}}"
INSTALL_DIR="/usr/local/bin"
GRPC_ADDR="{{.GRPCAddr}}"
ENROLL_TOKEN="{{.EnrollToken}}"

echo "==> Downloading Scout agent..."
if command -v curl &>/dev/null; then
  curl -fsSL -o "/tmp/${BINARY_NAME}" "${BINARY_URL}"
elif command -v wget &>/dev/null; then
  wget -qO "/tmp/${BINARY_NAME}" "${BINARY_URL}"
else
  echo "ERROR: curl or wget is required to download the Scout binary." >&2
  exit 1
fi

echo "==> Installing to ${INSTALL_DIR}/${BINARY_NAME}..."
install -m 755 "/tmp/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
rm -f "/tmp/${BINARY_NAME}"

{{if eq .Platform "linux"}}
# --- Linux-specific: systemd service ---
echo "==> Creating scout system user..."
if ! id -u scout &>/dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin scout
fi

echo "==> Creating config directory..."
mkdir -p /etc/scout

echo "==> Installing systemd service unit..."
cat > /etc/systemd/system/scout.service <<UNIT
[Unit]
Description=SubNetree Scout Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=scout
ExecStart=${INSTALL_DIR}/${BINARY_NAME} --server ${GRPC_ADDR}
Restart=on-failure
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable scout.service
{{end}}

echo "==> Enrolling Scout agent with server..."
"${INSTALL_DIR}/${BINARY_NAME}" --server "${GRPC_ADDR}" --enroll-token "${ENROLL_TOKEN}"

{{if eq .Platform "linux"}}
echo "==> Starting Scout service..."
systemctl start scout.service
{{end}}

echo ""
echo "Scout agent installed successfully!"
echo "  Binary:  ${INSTALL_DIR}/${BINARY_NAME}"
echo "  Server:  ${GRPC_ADDR}"
{{if eq .Platform "linux"}}
echo ""
echo "Useful commands:"
echo "  sudo systemctl status scout    # Check service status"
echo "  sudo journalctl -u scout -f    # Follow logs"
echo "  sudo systemctl restart scout   # Restart agent"
{{end}}
`))

// windowsInstallTemplate is built with string concatenation because Go raw strings
// use backticks, which conflict with PowerShell's backtick escape character.
var windowsInstallTemplate = template.Must(template.New("windows-install").Parse(
	"#Requires -RunAsAdministrator\r\n" +
		"$ErrorActionPreference = \"Stop\"\r\n" +
		"\r\n" +
		"# SubNetree Scout Agent Installer\r\n" +
		"# Version: {{.Version}}\r\n" +
		"# Platform: {{.Platform}}/{{.Arch}}\r\n" +
		"# Generated by SubNetree server at {{.ServerHost}}\r\n" +
		"\r\n" +
		"$BinaryURL   = \"{{.BinaryURL}}\"\r\n" +
		"$BinaryName  = \"{{.BinaryName}}\"\r\n" +
		"$InstallDir  = \"$env:ProgramFiles\\SubNetree\"\r\n" +
		"$BinaryPath  = \"$InstallDir\\$BinaryName\"\r\n" +
		"$GRPCAddr    = \"{{.GRPCAddr}}\"\r\n" +
		"$EnrollToken = \"{{.EnrollToken}}\"\r\n" +
		"$ServiceName = \"SubNetreeScout\"\r\n" +
		"\r\n" +
		"Write-Host \"==> Creating install directory...\" -ForegroundColor Cyan\r\n" +
		"if (-not (Test-Path $InstallDir)) {\r\n" +
		"    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null\r\n" +
		"}\r\n" +
		"\r\n" +
		"Write-Host \"==> Downloading Scout agent...\" -ForegroundColor Cyan\r\n" +
		"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12\r\n" +
		"Invoke-WebRequest -Uri $BinaryURL -OutFile $BinaryPath -UseBasicParsing\r\n" +
		"\r\n" +
		"Write-Host \"==> Enrolling Scout agent with server...\" -ForegroundColor Cyan\r\n" +
		"& $BinaryPath --server $GRPCAddr --enroll-token $EnrollToken\r\n" +
		"if ($LASTEXITCODE -ne 0) {\r\n" +
		"    Write-Error \"Enrollment failed with exit code $LASTEXITCODE\"\r\n" +
		"    exit 1\r\n" +
		"}\r\n" +
		"\r\n" +
		"Write-Host \"==> Installing Windows service...\" -ForegroundColor Cyan\r\n" +
		"$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue\r\n" +
		"if ($existing) {\r\n" +
		"    Write-Host \"    Service already exists, stopping...\" -ForegroundColor Yellow\r\n" +
		"    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue\r\n" +
		"    sc.exe delete $ServiceName | Out-Null\r\n" +
		"    Start-Sleep -Seconds 2\r\n" +
		"}\r\n" +
		"New-Service -Name $ServiceName " +
		"`" + "\r\n" +
		"    -DisplayName \"SubNetree Scout Agent\" " +
		"`" + "\r\n" +
		"    -BinaryPathName \"$BinaryPath --server $GRPCAddr\" " +
		"`" + "\r\n" +
		"    -StartupType Automatic " +
		"`" + "\r\n" +
		"    -Description \"SubNetree Scout monitoring agent\"\r\n" +
		"\r\n" +
		"Write-Host \"==> Starting Scout service...\" -ForegroundColor Cyan\r\n" +
		"Start-Service -Name $ServiceName\r\n" +
		"\r\n" +
		"Write-Host \"\"\r\n" +
		"Write-Host \"Scout agent installed successfully!\" -ForegroundColor Green\r\n" +
		"Write-Host \"  Binary:  $BinaryPath\"\r\n" +
		"Write-Host \"  Server:  $GRPCAddr\"\r\n" +
		"Write-Host \"  Service: $ServiceName\"\r\n" +
		"Write-Host \"\"\r\n" +
		"Write-Host \"Useful commands:\"\r\n" +
		"Write-Host \"  Get-Service $ServiceName              # Check service status\"\r\n" +
		"Write-Host \"  Restart-Service $ServiceName           # Restart agent\"\r\n" +
		"Write-Host \"  Get-EventLog -LogName Application -Source $ServiceName  # View logs\"\r\n",
))
